### ISSUE TITLE
前端问题

### ISSUE THREAD

**Issue by Null-Point-er** [jkkwjk/LeaveManagement#13]
非常抱歉打扰您，我现在遇到一个问题，前端项目跑起来之后，学生端的请假申请以及教师院领导端的请假审批都会报一个错误：TypeError: Cannot set property 'dateutil' of undefined
![image](https://user-images.githubusercontent.com/61180671/115249846-9a6f1880-a15b-11eb-948b-187b65fe7bf0.png)

**Comment by jkkwjk** [comment]
hi，请按照以下步骤进行排查
1. 首先请确保java程序没有异常错误
2. 如果错误发生在请求中 查看返回信息有无异常值
3. 点击 `LeaveApply.vue?6c48:1` 查看具体报错行
